services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi-backend-template
    image: fastapi-backend-template
    command: uvicorn api:app --host 0.0.0.0 --port 8081
    ports:
      - "8081:8081"
